name = "news-worker"
main = "worker/index.js"
compatibility_date = "2024-01-01"

workers_dev = true

# Default environment
kv_namespaces = [
    { binding = "RSS_CACHE", id = "${RSS_CACHE_KV_ID_DEFAULT}" }
]

[vars]
ENVIRONMENT = "development"
OPENAI_API_KEY = "${OPENAI_API_KEY}"

# Development environment
[env.development]
kv_namespaces = [
    { binding = "RSS_CACHE", id = "${RSS_CACHE_KV_ID_DEV}" }
]

[env.development.vars]
ENVIRONMENT = "development"
OPENAI_API_KEY = "${OPENAI_API_KEY}"

# Production environment
[env.production]
kv_namespaces = [
    { binding = "RSS_CACHE", id = "${RSS_CACHE_KV_ID_PROD}" }
]

[env.production.vars]
ENVIRONMENT = "production"
OPENAI_API_KEY = "${OPENAI_API_KEY}"
