name = "news-worker"
main = "worker/index.js"
compatibility_date = "2024-01-01"

workers_dev = true

[vars]
ENVIRONMENT = "development"
OPENAI_API_KEY = "${OPENAI_API_KEY}"

[env.production.vars]
ENVIRONMENT = "production"
OPENAI_API_KEY = "${OPENAI_API_KEY}"
